<?php

/**
 * CareersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CareersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CareersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Careers');
    }
    
    public static function getOne($job_id) {
        return Doctrine_Query::create()
                        ->select('c.*')
                        ->from('Careers c')
                        ->where('c.id =?', $job_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }
    
    public static function getAllActiveJobs($active_only = TRUE) {
        $q = Doctrine_Query::create()
                ->select('c.*')
                ->from('Careers c')
                ->where('c.deleted=0');
        if ($active_only) {
            $q = $q->andWhere('c.active_flag=?', $active_only);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('c.order_flag ASC')
                ->execute();
        
        return $q;
    }
}