<?php

/**
 * ConsultingExpert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ConsultingExpert extends BaseConsultingExpert
{
    public function updateConsultingExpert(array $data) {
        $contact = ConsultingExpertTable::getOne();
        
        $errors = $this->__validateContact($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('ConsultingExpert e')
                    ->set('e.name', '?', $data['name'])
                    ->set('e.job_title', '?', $data['job_title'])
                    ->set('e.photo', '?', $errors['photo'])
                    ->set('e.tel', '?', $data['tel'])
                    ->set('e.updated_at', '?', date('ymdHis'))
                    ->where('e.id =?', $contact['id'])
                    ->execute();

            return $errors;
        }
    }

    private function __validateContact($consulting_data) {
        $errors = array();
        $error_flag = false;       
        if (!required($consulting_data['job_title'])) {
            $errors['job_title'] = 'Please write in job title';
            $error_flag = true;
        }
        if (!required($consulting_data['name'])) {
            $errors['name'] = 'Please write in name';
            $error_flag = true;
        }
        if (!required($consulting_data['tel'])) {
            $errors['tel'] = 'Please write in phone';
            $error_flag = true;
        }

        if (!$error_flag && (isset($_FILES['userfile']) && !empty($_FILES['userfile']['name']))) {
            $upload_data = upload_file('consulting', array('jpg|png|jpeg|gif'), '2028');
            if ($upload_data['error_flag']) {
                $errors['photo'] = $upload_data['errors'];
                $error_flag = true;
            } else {
                $errors['photo'] = $upload_data['upload_data']['file_name'];
            }
        }else {
            $errors['photo'] = $consulting_data['same_photo'];
        }
        $errors['error_flag'] = $error_flag;

        return $errors;
    }
}