<?php

/**
 * ContactList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContactList extends BaseContactList {

    public function addOption(array $data) {
        $errors = $this->__validateOption($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $o = new ContactList();
            $o->lang_id = $data['lang_id'];
            $o->contact_option = $data['contact_option'];
            $o->created_at = date('ymdHis');
            $o->save();

            return $errors;
        }
    }

    public function updateOption(array $data) {
        $errors = $this->__validateOption($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('ContactList c')
                    ->set('c.contact_option', '?', $data['contact_option'])
                    ->set('c.updated_at', '?', date('ymdHis'))
                    ->where('c.id =?', $data['id'])
                    ->execute();

            return $errors;
        }
    }

    private function __validateOption(array $_data) {
        $errors = array();
        $error_flag = false;
        if (!required($_data['contact_option'])) {
            $errors['contact_option'] = 'Please write in option';
            $error_flag = true;
        }
        
        $errors['error_flag'] = $error_flag;

        return $errors;
    }
    
    public function deleteOption($option_id) {
        Doctrine_Query::create()
                ->update('ContactList c')
                ->set('c.deleted', '?', true)
                ->where('c.id =?', $option_id)
                ->execute();
    }

    public function options_sorting(array $data) {
        for ($i = 0; $i < count($data['order_flag']); $i++) {
            Doctrine_Query::create()
                    ->update('ContactList c')
                    ->set('c.order_flag', '?', $i)
                    ->where('c.id =?', $data['order_flag'][$i])
                    ->execute();
        }
    }

}
