<?php

/**
 * ContactListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactListTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ContactListTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ContactList');
    }

    public static function getOne($id) {
        return Doctrine_Query::create()
                        ->select('c.*')
                        ->from('ContactList c')
                        ->where('c.id=?', $id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getAllOptions() {
        $q = Doctrine_Query::create()
                ->select('c.*')
                ->from('ContactList c')
                ->where('c.deleted=0')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('c.order_flag ASC')
                ->execute();

        return $q;
    }

}
