<?php

/**
 * Contacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contacts extends BaseContacts
{
    public function addContact(array $data){
        $newsletter = false;
        if(isset($data['newsletter'])){
            $newsletter = true;
        }
        
        $c = new Contacts();
        $c->iam = $data['iam'];
        $c->title = $data['title'];
        $c->surname = $data['surname'];
        $c->given_name = $data['given_name'];
        $c->email = $data['email'];
        $c->phone = $data['phone'];
        $c->company = $data['company'];
        $c->function = $data['function'];
        $c->message = $data['message'];
        $c->newsletter = $newsletter;
        $c->created_at = date('ymdHis');
        $c->save();
    }
}