<?php

/**
 * EventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Events');
    }
    
    public static function getOne($event_id) {
        return Doctrine_Query::create()
                        ->select('e.*')
                        ->from('Events e')
                        ->where('e.id =?', $event_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getActiveEvents($limit = FALSE) {
        $q = Doctrine_Query::create()
                ->select('e.*')
                ->from('Events e')
                ->where('e.deleted =?', FALSE);
        if ($limit) {
            $q = $q->limit($limit);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('e.date DESC')
                ->execute();

        return $q;
    }

    public static function getEventsCount() {
        return Doctrine_Query::create()
                        ->select('count(e.id) as count')
                        ->from('Events e')
                        ->where('e.deleted =?', FALSE)
                        ->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR)
                        ->fetchOne();
    }
}