<?php

/**
 * ExpertsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpertsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ExpertsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Experts');
    }
    
    public static function getOne($expert_id) {
        return Doctrine_Query::create()
                        ->select('e.*')
                        ->from('Experts e')
                        ->where('e.id =?', $expert_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getAllActiveExperts($active_only = true, $lang_id = 1) {
        $q = Doctrine_Query::create()
                ->select('e.*')
                ->from('Experts e')
                ->where('e.deleted=0')
                ->andWhere('e.lang_id =?', $lang_id);
        if ($active_only) {
            $q = $q->andWhere('e.hide=?', FALSE);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('e.order_flag ASC')
                ->execute();
        
        return $q;
    }

}