<?php

/**
 * NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object NewsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('News');
    }

    public static function getOne($news_id) {
        return Doctrine_Query::create()
                        ->select('n.*')
                        ->from('News n')
                        ->where('n.id =?', $news_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getActiveNews($limit = FALSE, $excepted_id = '', $show_in_homepage = false) {
        $q = Doctrine_Query::create()
                ->select('n.*')
                ->from('News n')
                ->where('n.deleted =?', FALSE);
        if ($excepted_id) {
            $q = $q->andWhere('n.id !=?', intval($excepted_id));
        }
        if ($show_in_homepage) {
            $q = $q->andWhere('n.set_in_homepage =?', true);
        }
        if ($limit) {
            $q = $q->limit($limit);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('n.order_flag DESC')
                ->execute();

        return $q;
    }
    
    public function getBlogIdByBlogAlias($alias_url) {
        return Doctrine_Query::create()
                        ->select('n.id')
                        ->from('News n')
                        ->where('n.alias_url =?', $alias_url)
                        ->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR)
                        ->fetchOne();
    }

    public static function getNewsCount() {
        return Doctrine_Query::create()
                        ->select('count(n.id) as count')
                        ->from('News n')
                        ->where('n.deleted =?', FALSE)
                        ->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR)
                        ->fetchOne();
    }
    
    public static function setInHomepageOrNot($news_id, $status){
        Doctrine_Query::create()
                ->update('News n')
                ->set('n.set_in_homepage', '?', $status)
                ->where('n.id =?', $news_id)
                ->execute();
    }

}
