<?php

/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews {

    public function addNews(array $data) {
        $errors = $this->__validateNews($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $set_in_homepage = false;
            if (isset($data['set_in_homepage'])) {
                $set_in_homepage = true;
            }

            $n = new News();
            $n->title = $data['title'];
            $n->description = $data['description'];
            $n->image = $errors['news_image'];
            $n->set_in_homepage = $set_in_homepage;
            $n->created_at = date('ymdHis');
            $n->save();

            return $errors;
        }
    }

    public function updateNews(array $data) {
        $errors = $this->__validateNews($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $set_in_homepage = false;
            if (isset($data['set_in_homepage'])) {
                $set_in_homepage = true;
            }

            Doctrine_Query::create()
                    ->update('News n')
                    ->set('n.title', '?', $data['title'])
                    ->set('n.description', '?', $data['description'])
                    ->set('n.image', '?', $errors['news_image'])
                    ->set('n.set_in_homepage', '?', $set_in_homepage)
                    ->set('n.updated_at', '?', date('ymdHis'))
                    ->where('n.id =?', $data['id'])
                    ->execute();

            return $errors;
        }
    }

    public function deleteNews($news_id) {
        Doctrine_Query::create()
                ->update('News n')
                ->set('n.deleted', '?', TRUE)
                ->where('n.id =?', $news_id)
                ->execute();
    }

    private function __validateNews($news_data) {
        $errors = array();
        $error_flag = false;
        if (!required($news_data['title'])) {
            $errors['title'] = 'Please write in news title';
            $error_flag = true;
        }
        if (!required($news_data['description'])) {
            $errors['description'] = 'Please write in news brief';
            $error_flag = true;
        }
        if (isset($news_data['set_in_homepage']) && !required($news_data['set_in_homepage'])) {
            $errors['set_in_homepage'] = 'Please write in caption header';
            $error_flag = true;
        }

        if (!$error_flag) {
            $upload_data = upload_file('news', array('jpg|png|jpeg|gif'), '2028');
            if ($upload_data['error_flag']) {
                $errors['image'] = $upload_data['errors'];
                $error_flag = true;
            } else {
                $errors['news_image'] = $upload_data['upload_data']['file_name'];
            }
        }
        $errors['error_flag'] = $error_flag;

        return $errors;
    }

}