<?php

/**
 * PressClippingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressClippingTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PressClippingTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PressClipping');
    }

    public static function getOne($clipping_id) {
        return Doctrine_Query::create()
                        ->select('c.*')
                        ->from('PressClipping c')
                        ->where('c.id =?', $clipping_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getAllActivePressClippings($active_only = TRUE) {
        $q = Doctrine_Query::create()
                ->select('c.*')
                ->from('PressClipping c')
                ->where('c.deleted=0');
        if ($active_only) {
            $q = $q->andWhere('c.is_active=?', TRUE);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('c.order_flag ASC')
                ->execute();

        return $q;
    }

}