<?php

/**
 * ProductFeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFeatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductFeatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductFeature');
    }
    
    public static function getOne($feature_id) {
        return Doctrine_Query::create()
                        ->select('f.*')
                        ->from('ProductFeature f')
                        ->where('f.id =?', $feature_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getActiveFeature($limit = FALSE, $lang_id = 1) {
        $q = Doctrine_Query::create()
                ->select('f.*')
                ->from('ProductFeature f')
                ->where('f.deleted =?', FALSE)
                ->andWhere('f.lang_id=?', $lang_id);
        if ($limit) {
            $q = $q->limit($limit);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->orderBy('f.order_flag ASC')
                ->execute();

        return $q;
    }

    public static function getEventsCount() {
        return Doctrine_Query::create()
                        ->select('count(f.id) as count')
                        ->from('ProductFeature f')
                        ->where('f.deleted =?', FALSE)
                        ->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR)
                        ->fetchOne();
    }
}