<?php

/**
 * Quotes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Quotes extends BaseQuotes
{
    public function addQuote(array $data) {
        $errors = $this->__validateQuote($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $is_active = false;
            if (isset($data['is_active'])) {
                $is_active = true;
            }
            $b = new Quotes();
            $b->description = $data['description'];
            $b->author = $data['author'];
            $b->logo = $errors['news_image'];
            $b->title = $data['title'];
            $b->is_active = $is_active;
            $b->created_at = date('ymdHis');
            $b->save();

            return $errors;
        }
    }

    public function updateQuote(array $data) {
        $errors = $this->__validateQuote($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $is_active = false;
            if (isset($data['is_active'])) {
                $is_active = true;
            }

            Doctrine_Query::create()
                    ->update('Quotes b')
                    ->set('b.description', '?', $data['description'])
                    ->set('b.author', '?', $data['author'])
                    ->set('b.logo', '?', $errors['news_image'])
                    ->set('b.is_active', '?', $is_active)
                    ->set('b.updated_at', '?', date('ymdHis'))
                    ->where('b.id =?', $data['id'])
                    ->execute();

            return $errors;
        }
    }

    public function deleteQuote($quote_id) {
        Doctrine_Query::create()
                ->update('Quotes b')
                ->set('b.deleted', '?', TRUE)
                ->where('b.id =?', $quote_id)
                ->execute();
    }

    private function __validateQuote($quotes_data) {
        $errors = array();
        $error_flag = false;
        if (!required($quotes_data['description'])) {
            $errors['description'] = 'Please write in brief';
            $error_flag = true;
        }
        if (!required($quotes_data['author'])) {
            $errors['author'] = 'Please write in author';
            $error_flag = true;
        }

        if (!$error_flag) {
            $upload_data = upload_file('quotes', array('jpg|png|jpeg|gif'), '2028');
            if ($upload_data['error_flag']) {
                $errors['image'] = $upload_data['errors'];
                $error_flag = true;
            } else {
                $errors['news_image'] = $upload_data['upload_data']['file_name'];
            }
        }
        $errors['error_flag'] = $error_flag;

        return $errors;
    }
}