<?php

/**
 * StaticPages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StaticPages extends BaseStaticPages {
    
    public function updatepress(array $data) {
        $errors = $this->__validate($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('StaticPages p')
                    ->set('p.title', '?', $data['title'])
                    ->set('p.description', '?', $data['description'])                   
                    ->set('p.updated_at', '?', date('ymdHis'))
                    ->where('p.page_id =?', $data['page_id'])
                    ->execute();

            return $errors;
        }
    }

    private function __validate($data) {
        $errors = array();
        $error_flag = false;

        if (!required($data['title'])) {
            $errors['title'] = 'Please write in title';
            $error_flag = true;
        }
        if (!required($data['description'])) {
            $errors['description'] = 'Please write in brief';
            $error_flag = true;
        }
        $errors['error_flag'] = $error_flag;

        return $errors;
    }

}